# Generated by Django 4.0.1 on 2022-01-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ame',
            new_name='name',
        ),
    ]
